---
- name: "Create New user on Windows Machine"
  hosts: "{{ NODES }}"
  tasks:
    - name: "Check Windows machines access using win_ping"
      win_ping:
      when: ansible_os_family == 'Windows'

    - name: Create a new User 
      win_user:
        name: john1
        password: MyP4ssw0rd
        state: present
        #state: absent
        groups:
          - Users
      when: ansible_os_family == 'Windows'

# ansible-playbook userAdd.yml -e "NODES=192.168.9.126"
