---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 8640
      when: ansible_distribution == 'Debian'

    - name: Install unzip.
      package:
        name: unzip
      changed_when: false
