---
  - name:  Install packages in Ubuntu/Debian.
    import_tasks: Debian.yml
    when: ansible_os_family == 'Debian' and ansible_distribution_major_version == '20'

  - name:  Install packages in CentOS/RedHat.
    import_tasks: RedHat.yml
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
# - name: Include OS-specific tasks
#   include_tasks: "{{ item }}"
#   with_first_found: 
#     - files:
#       # - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
#       # - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
#       # - "{{ ansible_distribution }}.yml"
#       - "{{ ansible_os_family }}.yml"
#       skip: true