---
  - name: using roles to install packages...
    import_tasks: redhat.yml
    #when: ansible_os_family == "RedHat"
    when: ansible_distribution == "CentOS"


  - name: using roles to install packages...
    import_tasks: ubuntu.yml
    when: ansible_distribution == "Ubuntu"
