---
- hosts: all
  tasks: 
  - name: install
    yum: 
     name: finger
     state: present
  - name: clone Repo
    git: 
      repo: https://github.com/Niranjan2211/JsonPath.git
      dest: /tmp/JsonPath 
