---
- hosts: all
  tasks:
    - stat: path=/etc/sysconfig/network-scripts/ifcfg-enp0s3
      register: niru

    - lineinfile:
      path: '/etc/sysconfig/network-scripts/ifcfg-enp0s3'
      regexp: '^LINKDELAY='
      line: 'LINKDELAY=20'

  when: niru.stat.exists == True
      
